redis:
  image: redis

couch:
  image: couchdb

hookio:
  build: .
  ports:
    - "49160:9999"
  links:
    - "redis:redis"
    - "couch:couch"
    - "worker0:worker0"

worker0:
  image: worker
  ports:
    - "49161:10000"
  links:
    - "redis:redis"
    - "couch:couch"