redis:
  image: redis

couch:
  build: ./docker/couchdb

hookio:
  build: .
  ports:
    - "49160:9999"
  links:
    - "redis:redis"
    - "couch:couch"
    - "worker:worker"

worker:
  build: ./docker/worker
  privileged: true
  ports:
    - "49161:10000"
  links:
    - "redis:redis"
    - "couch:couch"