redis:
  image: redis

couch:
  build: ./docker/couchdb

hookio:
  build: .
  command: node /src/bin/server
  ports:
    - "49160:9999"
  links:
    - "redis:redis"
    - "couch:couch"
    - "worker:worker"

worker:
  build: .
  command: node /src/bin/worker
  privileged: true
  ports:
    - "49161:10000"
  links:
    - "redis:redis"
    - "couch:couch"

setup:
  build: .
  command: /src/config/couchdb/create_admin.sh
  links:
    - "couch:couch"